name: Run Telegram Bot

on:
  schedule:
    - cron: '20 14 * * *'  # Запускается ежедневно в 14:20 UTC
  workflow_dispatch: # Возможность запуска вручную

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Telegram Bot Script
        run: python telegram_bot.py
